#!/usr/bin/env ruby

require_relative 'lib/raven'
require 'pp'

File.open('/dev/ttyUSB0', 'r+') do |f|
  # raven = Raven::Device.new(f)

  # puts raven.get_time

  # raven.run! do |notification|
  #   puts notification
  # end


  parser = Raven::Internal::BasicXmlParser.new(f)
  last_full_check = 0

#   f << "<Command>
#   <Name>close_current_period</Name>
# </Command>"

  loop do
    if Time.now.to_i / 30 > last_full_check
#       f << "<Command>
#   <Name>get_current_summation_delivered</Name>
#   <Refresh>Y</Refresh>
# </Command>"
#       f << "<Command>
#   <Name>get_current_period_usage</Name>
#   <Refresh>Y</Refresh>
# </Command>"
      f << "<Command>
  <Name>get_profile_data</Name>
  <NumberOfPeriods>12</NumberOfPeriods>
  <EndTime>0</EndTime>
  <IntervalChannel>Delivered</IntervalChannel>
</Command>"
      last_full_check = Time.now.to_i / 30
    end

    message_type, message_data = parser.next
    puts Raven::Notification.build(message_type, message_data)
  end
end
