#!/usr/bin/env ruby

require_relative 'lib/raven'

File.open('/dev/ttyUSB0') do |f|
  parser = Nokogiri::XML::SAX::PushParser.new(Raven::Internal::Collector.new(Raven::Internal::Processor.new))

  parser << "<Stream>"

  while true
    line = f.gets
    line.gsub!("\0", '')   # seems to send through a bunch of nulls
    
#    puts line.inspect
    parser << line
  end
  
  parser "</Stream>"
  
  parser.finish
end
